//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMVC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessZone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccessZone()
        {
            this.Devices = new HashSet<Device>();
            this.EmployeeAccessZoneMaps = new HashSet<EmployeeAccessZoneMap>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Floor { get; set; }
        public string Description { get; set; }
        public Nullable<int> CommonZone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Device> Devices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeAccessZoneMap> EmployeeAccessZoneMaps { get; set; }
    }
}
