//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMVC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Id { get; set; }
        public string UserBy { get; set; }
        public string UserTo { get; set; }
        public string Purpose { get; set; }
        public string RequestDetails { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> AppointmentStatusId { get; set; }
    
        public virtual AspNetUser AspNetUserBy { get; set; }
        public virtual AspNetUser AspNetUserTo { get; set; }
        public virtual AppointmentStatu AppointmentStatu { get; set; }
    }
}
