//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMVC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardLog
    {
        public int Id { get; set; }
        public int CardId { get; set; }
        public System.DateTime Time { get; set; }
        public int DeviceId { get; set; }
    
        public virtual CardInfo CardInfo { get; set; }
        public virtual DeviceInfo DeviceInfo { get; set; }
    }
}
