//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMVC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.CardLogs = new HashSet<CardLog>();
            this.DeviceCardMaps = new HashSet<DeviceCardMap>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string IP { get; set; }
        public string Port { get; set; }
        public string DeviceSDK { get; set; }
        public string DUser { get; set; }
        public string DPass { get; set; }
        public int AccessZoneId { get; set; }
        public int DeviceTypeId { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual AccessZone AccessZone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CardLog> CardLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceCardMap> DeviceCardMaps { get; set; }
        public virtual DeviceType DeviceType { get; set; }
        public virtual Device Device1 { get; set; }
        public virtual Device Device2 { get; set; }
        public virtual Status Status { get; set; }
    }
}
