//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace ACMVC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCardMap
    {
        public int Id { get; set; }
        public int CardId { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.DateTime RevocationDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Notes { get; set; }
        public string UserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual CardInfo CardInfo { get; set; }
        public virtual Status Status { get; set; }

        [NotMapped]
        public string UserEmail { get; set; }
        [NotMapped]
        public string CardIdNumber { get; set; }
    }
}
