//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMVC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleInfo
    {
        public long Id { get; set; }
        public string VehicleId { get; set; }
        public string VehicleNo { get; set; }
        public string OwnerName { get; set; }
        public string OwnerAddress { get; set; }
        public string DriverName { get; set; }
        public string DriverDetails { get; set; }
        public string LicenseNo { get; set; }
        public string IsDelete { get; set; }
        public string Status { get; set; }
        public string TagNumber { get; set; }
        public Nullable<int> AccessType { get; set; }
        public Nullable<int> VehicleType { get; set; }
    }
}
